"""Updated deduction model

Revision ID: 11cb4be49ced
Revises: e59307b24b35
Create Date: 2026-01-09 09:47:05.270763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11cb4be49ced'
down_revision: Union[str, Sequence[str], None] = 'e59307b24b35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deduction_types', sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'SUSPENDED', 'CANCELLED', name='deductionstatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deduction_types', 'status')
    # ### end Alembic commands ###
