"""initial schema

Revision ID: 490f351066e3
Revises: 
Create Date: 2026-01-02 10:20:02.805895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '490f351066e3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('regular_hours', sa.Float(), nullable=True))
    op.drop_column('attendance', 'status')
    op.create_index(op.f('ix_deduction_brackets_id'), 'deduction_brackets', ['id'], unique=False)
    op.create_index(op.f('ix_deduction_types_id'), 'deduction_types', ['id'], unique=False)
    op.create_index(op.f('ix_deductions_id'), 'deductions', ['id'], unique=False)
    op.drop_column('payrolls', 'processing_errors')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payrolls', sa.Column('processing_errors', sqlite.JSON(), nullable=True))
    op.drop_index(op.f('ix_deductions_id'), table_name='deductions')
    op.drop_index(op.f('ix_deduction_types_id'), table_name='deduction_types')
    op.drop_index(op.f('ix_deduction_brackets_id'), table_name='deduction_brackets')
    op.add_column('attendance', sa.Column('status', sa.VARCHAR(), nullable=True))
    op.drop_column('attendance', 'regular_hours')
    # ### end Alembic commands ###
