"""Updated Allowance models

Revision ID: e59307b24b35
Revises: 490f351066e3
Create Date: 2026-01-05 14:32:05.648705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e59307b24b35'
down_revision: Union[str, Sequence[str], None] = '490f351066e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   # op.drop_index(op.f('ix_tokens_expires_at'), table_name='tokens')
    #op.drop_index(op.f('ix_tokens_id'), table_name='tokens')
    #op.drop_index(op.f('ix_tokens_token'), table_name='tokens')
    #op.drop_table('tokens')
   # op.add_column('allowance_types', sa.Column('calculation_type', sa.Enum('FIXED', 'PERCENTAGE', name='allowancecalculationtype'), nullable=True))
   # op.add_column('allowance_types', sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'SUSPENDED', 'CANCELLED', name='allowancestatus'), nullable=False))
   #op.alter_column('allowance_types', 'percentage_of',
              # existing_type=sa.VARCHAR(length=50),
              # type_=sa.Enum('BASIC_SALARY', 'GROSS_SALARY', name='allowancepercentagebasis'),
              # existing_nullable=True)
    """
                op.drop_index(op.f('ix_allowancetype_is_active'), table_name='allowance_types')
    op.create_index('ix_allowancetype_status', 'allowance_types', ['status'], unique=False)
    op.drop_column('allowance_types', 'is_active')
    op.drop_column('allowance_types', 'is_percentage_based')
    op.drop_column('allowance_types', 'updated_at')
    op.drop_index(op.f('ix_allowance_status'), table_name='allowances')
    op.drop_column('allowances', 'status')
    op.drop_column('allowances', 'description')
    op.drop_column('allowances', 'updated_at')
    op.drop_column('allowances', 'reference_number')
              """
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('allowances', sa.Column('reference_number', sa.VARCHAR(length=100), nullable=True))
    op.add_column('allowances', sa.Column('updated_at', sa.DATETIME(), nullable=False))
    op.add_column('allowances', sa.Column('description', sa.TEXT(), nullable=True))
    op.add_column('allowances', sa.Column('status', sa.VARCHAR(length=9), nullable=False))
    op.create_index(op.f('ix_allowance_status'), 'allowances', ['status'], unique=False)
    op.add_column('allowance_types', sa.Column('updated_at', sa.DATETIME(), nullable=False))
    op.add_column('allowance_types', sa.Column('is_percentage_based', sa.BOOLEAN(), nullable=True))
    op.add_column('allowance_types', sa.Column('is_active', sa.VARCHAR(length=9), nullable=False))
    op.drop_index('ix_allowancetype_status', table_name='allowance_types')
    op.create_index(op.f('ix_allowancetype_is_active'), 'allowance_types', ['is_active'], unique=False)
    op.alter_column('allowance_types', 'percentage_of',
               existing_type=sa.Enum('BASIC_SALARY', 'GROSS_SALARY', name='allowancepercentagebasis'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('allowance_types', 'status')
    op.drop_column('allowance_types', 'calculation_type')
    op.create_table('tokens',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('token', sa.VARCHAR(), nullable=False),
    sa.Column('token_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('is_used', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    #op.create_index(op.f('ix_tokens_token'), 'tokens', ['token'], unique=1)
    #op.create_index(op.f('ix_tokens_id'), 'tokens', ['id'], unique=False)
    #op.create_index(op.f('ix_tokens_expires_at'), 'tokens', ['expires_at'], unique=False)
    # ### end Alembic commands ###
